export const WordTools = [
  {
    image: './word-file.png',
    alt: 'word to pdf',
    title: 'Word to PDF',
    description: 'Make DOC  files easy to read by converting them to PDF.',
    link: 'word_to_pdf',
    from: 'word',
    to: 'pdf',
    type: 'Convert',
  },
  {
    image: './word-file.png',
    alt: 'docx to pdf',
    title: 'DOCX to PDF',
    description: 'Make  DOCX files easy to read by converting them to PDF.',
    link: 'docx_to_pdf',
    from: 'docx',
    to: 'pdf',
    type: 'Convert',
  },
  {
    image: './word-file.png',
    alt: 'word to jpg',
    title: 'Word to JPG',
    description: 'Convert Each JPG page into a JPG.',
    link: 'word_to_jpg',
    from: 'word',
    to: 'jpg',
    type: 'Convert',
  },
];
